title: Wyatt Harrell - Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Computer Science graduate from Florida State Univiversity. Currenly learning iOS Development at Lambda School.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://wyattharrell.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Wyatt Harrell # add your name
author-img: wyatt-harrell.png # add your photo
about-author: Computer Science graduate learning iOS Development at Lambda School # add description
social-twitter: wyatt_harrell # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: wyattharrell # add your Github handle
social-linkedin: wyattharrell # add your Linkedin handle
social-email: wyattaharrell@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
